spring.application.name=backend
#spring.config.import=classpath:.env[.properties]

server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${CLUSTER}/${BD}?retryWrites=true&w=majority
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration